SELECT * FROM Customers

UPDATE Customers
SET NATION= 'TR', AGE=DATEDIFF(YEAR,BIRTHDAY,GETDATE())

/*
DATEDIFF FONKSİYONU BİZE İKİ TARİH ARASINDAKİ FARKI HESAPLAMAMIZA YARAYAN BİR FONKSİYONDUR.
YUKARIDA İSE VERİ GİRİŞİ YAPILAN TARİH İLE ŞİMDİKİ TARİH ARASINDAKİ FARKI YAZDIRMA İŞLEMİ YAPTIK.
*/



