--BİR MAĞZANIN GÜNLÜK BAZLI SATIŞLARINI GETİRME 
--TARİH ALANIMIZ HEM TARİH HEMDE SAAATTEN OLUŞUYOR. BUNU AYIRT ETTİRMEMİZ GEREKİYOR.
SELECT CONVERT(DATE,DATE_) AS DATE2,* --bu şekilde veya yeni bir alan ekleyerek yapabiliriz.
--DATE ALANIM TARİH SAAT TÜRÜNDE BEN BUNU 
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_

SELECT *
FROM SALES WHERE CITY='ANKARA'
ORDER BY DATE_
UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)


--CONVERT ATIŞTIRMASI
SELECT CONVERT(DATE,'2019-01-01 08:46:10.000') --SADECE TARİH BİLGİSİNİ ALDI. O FORMATA DÖNÜŞTÜRDÜ DEMEK.
SELECT CONVERT(TIME,'2019-01-01 08:46:10.000') --SADECE TIME BİLGİSİNİ ALDI. O FORMATA ÇEVİRDİ DEMEK.
SELECT CONVERT(DATETIME,'2019-01-01 08:46:10.000') --HEM DATE HEM DATE OLARAK BİRLEŞTİRİP TEK PARÇADA BANA GETİRDİ.
