SELECT 
CITY ,
MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE)
FROM SALES   --BU ŞEKİLDE YAZAMAYIZ YA AGREGETE FOKSİYONU İÇİNDE GEÇMELİ YADA  GRUP BY İÇİNDE VERMEK GEREK.

--1.YOL
--SELECT 
--COUNT(CITY) ,
--MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE)
--FROM SALES

--VEYA
SELECT 
CITY ,
MIN(TOTALPRICE) AS MINPRICE,
MAX(TOTALPRICE) AS MAXPRICE,
COUNT(FICHENO) ROWCOUNT_,
SUM(TOTALPRICE) TOTALPRICE,
AVG(TOTALPRICE) AVGPRICE
FROM SALES
GROUP BY CITY
--ORDER BY CITY
ORDER BY SUM(TOTALPRICE) --Toplamlarını sırala diyoruz.
--AS İLE KOLON İSMİ VERİYORUZ

--EN ÇOK SATIŞ YAPAN MAĞAZALARIMI GÖRMEK İSTİYORUM.
SELECT 
CITY,SUM(TOTALPRICE) AS MAĞAZA_SATIŞ
FROM SALES

GROUP BY CITY --ŞEHİRLERE GÖRE SATIŞLARI GETİRMEK İÇİN KULLANDIK.
ORDER BY SUM(TOTALPRICE) DESC --SATIŞLAR TOPLAMINI YÜKSEKTEN KÜÇÜĞE DOĞRU SIRALAMA YAP DİYORUZ.

--EN ÇOK SATIŞ YAPAN 10 MAĞAZAMI GÖSTER BANA DİYORUZ.
SELECT TOP 10
CITY,SUM(TOTALPRICE) AS MAĞAZA_SATIŞ
FROM SALES
GROUP BY CITY 
ORDER BY SUM(TOTALPRICE) DESC

--TOPLAM CİROSUNA GÖRE EN ÇOK SATIŞ YAPAN İLLERİ BU ŞEKİLDE GETİRMİŞ OLDUK