--BELLİ BİR CİRONUN ÜZERİNDE SATIŞ YAPAN MAĞAZALARI GETİRME ÖRNEĞİ YAPACAĞIZ.
SELECT * FROM SALES
--Burada cirolarına göre şehirlerimi listeledim
SELECT CITY,SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

--40.000 den fazla ciro yapanları getir diyelim.
SELECT CITY,SUM(TOTALPRICE)
FROM SALES
WHERE TOTALPRICE>40000 --KAYIT GELMEDİ VE GROUP BY OLMADAN DENE.
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

SELECT * FROM SALES WHERE TOTALPRICE>40000
--KAYIT GENE GELMEDİ. TOTAL PRICE İÇİNDE TEK TEK KONTROL EDER VE BÖYLE BİR KAYIT BULAMAZ.
--Bir şehrin toplam cirosu 40.000 den büyükmü küçük mü buna bakmam lazım.
--!!!
SELECT CITY,SUM(TOTALPRICE)
FROM SALES
WHERE SUM(TOTALPRICE)>40000 
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC --HATA!!!= AGGREGATE FONKSİYONU BİR WHERE ŞARTI İÇİNDE KULLANAMAZSIN DİYOR .
/*
NOT : Sen eğer bir aggregate fonksiyonu group by içerisinde kullanıyorsan , bunu where şartında kullanmazsın diyor . Böyle bir şeye ihtiyaç
varsa bunu HAVING ile kullanabilirsin diyor.
Ancak where şartı ekleme hiç yapılamaz diye bir kaide yok. AGGREGATE FONKSİYON OLMAYAN standart kolon olan(CITY) kullandığım şeyler için
where şartı verebiliriz.SUM(TOTALPRICE) bu şekilde ben bir aggregate fonksiyon vermissem , bunu HAVING SUM(TOTALPRICE)>40000 bu şekilde 
having ile vermem gerekiyor.
*/

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES
--WHERE CITY IN ('ANKARA','İSTANBUL','İZMİR','AYDIN','HATAY')
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000 
ORDER BY SUM(TOTALPRICE) DESC --İSTANBULUN 6623 ADET MÜŞTERİSİ VARMIŞ VE İSTANBULUN TOPLAM CİROSUDA TOTALPRICE ALTINDA YAZIYOR.

--?? 2000 DEN BÜYÜK OLAN TEKİL MÜŞTERİLERİ GETİRELİMM...
SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>2000  
ORDER BY SUM(TOTALPRICE) DESC

--
SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>500   --Müşteri sayısı 500 den fazla tekil olanlar ve cirosu 300000 den fazla olanları getir demiş olduk.
AND SUM(TOTALPRICE)>300000
ORDER BY SUM(TOTALPRICE) DESC


