--TARİHE GÖRE SİPARİŞ DAĞILIMINI GETİREN SORGU
SELECT 
CONVERT(DATE,O.DATE_) TARIH,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID= OD.ID
GROUP BY CONVERT(DATE,O.DATE_)
ORDER BY CONVERT(DATE,O.DATE_)  

--AYLARA GÖRE HESAP YAPALIM  
--AYLARA GÖRE GECİKMELERİ ANALİZ EDELİM
SELECT
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH,O.DATE_) AS AY,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS ORTALAMA_TESLIMATSURESI_SAAT,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS EN_KISA_TESLIMATSURESI_SAAT,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS EN_UZUN_TESLIMATSURESI_SAAT,
SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
COUNT(O.ID) AS SIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID

GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_) 
ORDER BY 1,2 DESC


--AYLARA GÖRE SİPARİŞ DAĞILIMINI GETİREN SORGU
SELECT 
DATEPART(YEAR,O.DATE_) YIL,
DATEPART(MONTH,O.DATE_) AY,
--AYLARDA RAKAM YERİNE İSİM YAZMASINI İSTİYORSAK;
--OLMAYAN BİR ALANI CASE KOMUTU İLE GETİRMEYİ ÖĞRENDİK
--WHEN GÖNDERDİĞİM DEĞER ŞUNA EŞİTSE OCAK YAZIDR.
CASE
    WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
    WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ŞUBAT'
    WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
    WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NİSAN'
    WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYS'
    WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZİRAN'
    WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
    WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AĞUSTOS'
    WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
    WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİM'
    WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
    WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END AS AYADI,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID= OD.ID

GROUP BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)
--DATEPART TARİH İÇİNDEKİ DEĞERİN SADECE AY DEĞERİNİ GETİRİR.
--ORDER BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_) YIL VE AY YER DEĞİŞTİRİRSE AYLARA GÖRE DAĞILIM OLUR