--şEHİRLERE GÖRE VERİLEN TOPLAM SİPARİŞ TUTARLARINI HESAPLAYALIM.
SELECT 
CT.CITY SEHIRADI,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID= OD.ID
--WHERE U.USERNAME_ = 'C_GEZGINCI'

GROUP BY CT.CITY
--ORDER BY CT.CITY
--ORDER BY SUM(OD.LINETOTAL)  --EN YÜKSEK MEVLALI ŞEHİRLER SIRALI BİR ŞEKİLDE GELDİ.
ORDER BY 1--KOLON İSİMLENDİRMELERİNİBU ŞEKİLDEDE YAZABİLİYORDUK.

