--KULLANICININ SON ADRESİNİ BULMA
--Tüm kullanıcıların son adresinigetirelim
SELECT U.*,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID DESC) SONADRES,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID) ILKADRES,
(SELECT COUNT(ADDRESSTEXT) FROM ADDRESS WHERE USERID=U.ID ) ADRESSAYISI

FROM
USERS U 


