
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMA_FIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAM_ADET,
(
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
WHERE OD.ITEMID=ITM.ID --1 yerine ITM.ID Değerini gönderdik.
GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC --satış adedine göre tersden sıraladık.
) AS ENCOKSATILANAY
--kayıtları olmayan ürünleri görmek isterken başka bir subquery kullanabiliriz.

FROM
ITEMS ITM
--WHERE ITEMCODE IN ('10740','11396')
--WHERE (SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) IS NULL
WHERE ITM.ID NOT IN  --ORDERDETAILS TABLOSUNDA SİPARİŞİ OLMAYAN KAYITLARI GETİR DEMİŞ OLUYORUZ.
(SELECT ITEMID FROM ORDERDETAILS)
ORDER BY 3
