SELECT * FROM Customers

--WHERE COSTOMERNAME LIKE 'ALİ%' --ALİ İLE BAŞLAYANLARI LİSTELE DİYORUM. ALİ İLE BAŞLANGICI BU YÜZDE İFADESİ İSE SONU ÖNEMLİ DEĞİ DEMEK.

--SOYADI ALP İLE BİTENLERE BAKALIM
WHERE COSTOMERNAME LIKE '%ALP' --BAŞLANGICI ÖNEMLİ DEĞİL SONU ALP İLE BİTENLERİ GETİR. Yukarıdakinin tersi oluyor.