--ÜRÜNLERİN FİYAT ANALİZİ
SET STATISTICS IO ON --HANGİ TABLODAN NE KADAR OKUMA YAPIYOR.
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT, --select cümlesini bir kolon gibi kullanacağız
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMA_FIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET
/*
Sunquery dediğimiz iç içe select durumu var demek . Parantez içerisinde yazmış olduğumuz bir sql cümlesi var , parametre alır veya almaz.
join veya where yerine subquery mantığı ile , sorgumuzu getirdim .
*/
FROM
ITEMS ITM
ORDER BY ITM.ITEMNAME