DECLARE @NAMESURNAME AS VARCHAR(50)='' 
DECLARE @AGE AS INT
DECLARE @EMAIL AS VARCHAR(100)=''
DECLARE @MSG AS VARCHAR(500)

DECLARE CRS CURSOR FOR 
	SELECT  NAMESURNAME,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AS AGE,EMAIL 
		FROM USERS
	WHERE DAY(BIRTHDATE)=25 AND MONTH(BIRTHDATE)=4
OPEN CRS
FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL

WHILE @@FETCH_STATUS=0
BEGIN
SET @MSG ='Sayýn '+@NAMESURNAME+', Doðum gününüz kutlu olsun. '+CONVERT(VARCHAR,@AGE)+'. Yaþýnýzý kutlar, nice mutlu yýllar dileriz.'

EXEC msdb.dbo.sp_send_dbmail @profile_name='SQLMAIL',
@SUBJECT='MUTLU YILLAR',
@BODY=@MSG,
@recipients=@EMAIL



FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL
END
CLOSE CRS
DEALLOCATE CRS 
 




