--DÝNAMÝK VÝEW ÝLE ÇOK DAHA RAHAT BU ÝÞLEMLERÝ YAPABÝLÝRÝM.
CREATE VIEW VW_BUGUNDOGANLAR AS
SELECT 
NAMESURNAME AD_SOYAD,
'Sn' +'. '+ NAMESURNAME+' ' + GenderXp+'; ' +CONVERT(varchar,AGE) +'. yaþýnýzý kutlar ailenile birlikte nice mutlu yýllargeçirmenizi dilerim.' Message_
FROM 
(
SELECT 
NAMESURNAME,GENDER,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,BIRTHDATE,
IIF(GENDER='K','Haným','Bey') GenderXp
FROM USERS
WHERE DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE()) AND
DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())
) T