SELECT 
NAMESURNAME,GENDER,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,BIRTHDATE,
CASE 
WHEN GENDER = 'E' THEN 'Sn '+ NAMESURNAME +' Bey '+CONVERT(varchar,DATEDIFF(YEAR,BIRTHDATE,GETDATE()))+'. yaþýnýzý kutlar,ailenizle birlikte mutlu bir ömür dileriz.'
WHEN GENDER = 'K' THEN 'Sn '+ NAMESURNAME +' Haným '+CONVERT(varchar,DATEDIFF(YEAR,BIRTHDATE,GETDATE()))+'. yaþýnýzý kutlar,ailenizle birlikte mutlu bir ömür dileriz.'
END AS MASSAGE
FROM USERS
WHERE DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE()) AND
DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())




