CREATE VIEW VWINVOICEDURATION AS
SELECT CT.CITY,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) ORTALAMA_HAZIRLIK_SURESI
FROM ORDERS O 
INNER JOIN INVOICES I ON O.ID=I.ORDERID 
INNER JOIN ADDRESS A ON A.ID=I.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
GROUP BY CT.CITY