--ÜRÜN KATEGORİLERİNE GÖRE SATIŞ RAKAMLARINI GETİRME
SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE, --BURASI TOPLAM MİKTARI,PARASAL OLARAK NE KADAR SATILMIŞ
COUNT(*) AS ROWCOUNT_, --TOPLAM SATIR SAYISI
SUM(AMOUNT) AS TOTALAMOUNT --TOPLAM TUTAR,ADET OLARAK NE KADAR SATILMIŞ DEMEK

FROM SALES 
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4 --15 BİN SATIRI BEN GRUPLAYINCA BANA 786 ADET SATIR GELDİ.
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4

/*
SADECE KATEGORİ 1 E GÖRE SIRALAMA YAPARSAK 24 SATIR GELİR
SADECE KATEGORİ 1,KATEGORİ 2 E GÖRE SIRALAMA YAPARSAK 93 SATIR GELİR
*/