--Ürün kategorilerine göre sipariş dağılımını hesaplayalım .
SELECT 
ITM.CATEGORY1,ITM.CATEGORY2,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID= OD.ID
WHERE ITM.CATEGORY1='KOZMETIK'
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2  --KOZMETIK KAT. SATIŞI YAPILAN EN YÜKSEK ÜRÜNÜBU ŞEKİLDE BULABİLİRİZ.
ORDER BY 3 DESC

--ORTALAMA FİYATLARINI DA BULALIM HADEEE(BALIK DA MESELA 16 TL BİRİM FİYATI VAR.)
 SELECT 
ITM.CATEGORY1,ITM.CATEGORY2,
SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS  ORTALAMABIRIMFIYAT 
FROM ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID= OD.ID
--WHERE ITM.CATEGORY1='KOZMETIK'
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2  
ORDER BY 1 