--ORTALAMA TESLİMAT SÜRESİ
--SİPARİŞİN VERİLDİĞİ TARİH İLE FATURANIN KESİLDİĞİ TARİH ARASINDAKİ FARKI HESAPLAMAK
SELECT
--O.ID AS SIPARISID,     --AVG KULLANIYORSAK BUNLARI SİLİYORUZ
--O.DATE_ AS SIPARISTARIHI,
--I.DATE_ AS FATURATARIHI,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS ENKISA_TESLIMATSURESI_SAAT,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS ENKISA_TESLIMATSURESI_SAAT,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS TESLIMATSURESI_SAAT


FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
--INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
--INNER JOIN ITEMS ITM ON ITM.ID= OD.ID

--FARK ALMAK İÇİN DATEDIFF KULLANIYORUZ.
--SELECT DATEDIFF(DAY,'2019-02-05 23:56:58.000','2019-02-06 10:54:58.000')
--SELECT DATEDIFF(HOUR,'2019-02-05 23:56:58.000','2019-02-06 10:54:58.000')
--SELECT DATEDIFF(MINUTE,'2019-02-05 23:56:58.000','2019-02-06 10:54:58.000')


--ORDER BY SIPARISID