--AYLARA GÖRE GECİKMELERİ ANALİZ EDELİM
SELECT
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH,O.DATE_) AS AY,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS ORTALAMA_TESLIMATSURESI_SAAT,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS EN_KISA_TESLIMATSURESI_SAAT,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_ )) AS EN_UZUN_TESLIMATSURESI_SAAT,
SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_TUTARI,
COUNT(O.ID) AS SIPARIS_SAYISI
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID

GROUP BY 
DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_) 
ORDER BY 1,2 DESC