--ORDER BY 
--ORDER SIRA DEMEK ORDER BY İSE SIRALAMA YAPMAYA YARAMAKTADIR.
/*
KULLANIMI : 
SELECT 
KOLON1,KOLON2,KOLON3,..
FROM TABLOADI
WHERE <ŞARTLAR>
ORDER BY KOLON1 ASC, KOLON2 DESC,
KOLON3 ASC
ASC--A DAN Z YE VEYA KÜÇÜKTEN BÜYÜĞE GÖRE SIRALAMA YAPMAYA YARAR ASKENDİNG DİYE OKUNUR
DESC İSE BÜYÜKTEN KÜÇÜĞE GÖRE SIRALAMA YAPMAYA YARAR.
*/
SELECT * FROM Customers 
--HİÇBİR SIRALAMA ŞARTI VERMEDİĞİM İÇİN SIRALAMA PRİMARY KEY E GÖRE GERÇEKLEŞTİ. ID alanım ise otomatik artan olduğu için bu şekilde bir sıralama geldi.
--ORDER BY ID ASC --YUKARIDAKİ İLE DEFAULD LA AYNI SIRALAMA GELİR ASC küçükten büyüğe demek çünkü.

--ORDER BY ID DESC --BÜYÜKTEN KÜÇÜĞE ID YE GÖRE SIRALAMA YAPMIŞ OLUYORUZ.
--ASC VEYA DESC YAZMAZSAK DEFAULD OLARAK KÜÇÜKTEN BÜYÜĞE DOĞRU SIRALAMA YAPAR.

--ORDER BY COSTOMERNAME --A Dan Z ye doğru defauld(asc) olarak sıralama yapar.

--ORDER BY COSTOMERNAME DESC --Z DEN A YA DOĞRU BİR SIRALAMA YAPAR.
--NOT: F5 TUŞU İLE KISAYOL OLARAK ÇALIŞTIRMA YAPIYORUZ .EXECUTE

--ORDER BY CITY,COSTOMERNAME
--ADANA şhrinde costomernameleri a dan z ye sıralama yaptırdı.
--Daha sonra Adıyamandada costomername yi  a dan z ye sıralama yaptırdı ve bu şekilde  kolonu sıralamaya tabii tutturmuş olduk.

--Şimdi şehri a dan z ye doğru sıralama yapalım ama costomer name i ise z den a ya doğru sıralama yapalım.
--ORDER BY CITY,COSTOMERNAME DESC

--BİRDE WHERE ŞARTINA GÖRE SIRALAMA YAPALIM
--WHERE CITY ='İSTANBUL'
--ORDER BY CITY,DISTRICT,COSTOMERNAME 
--İLÇE VE İL AYNI OLUNCA  KİŞİ ARASINDA SIRALAMA YAPMAYA BAKMAKTADIR.

--KOLON SIRASINA GÖRE SIRALAMA 
WHERE CITY ='İSTANBUL'
ORDER BY 5,2 --2.KOLONA GÖRE SIRALAMA YAP DEMİŞ OLUYORUM.TABLO ADINI YAZMAM İLE COSTOMERNAME İLE 2 AYNI ANLAMA GELMEKTEDİR.