--ASCII FONKSİYONU -0 İLE 254 ARASINDA DEĞER DÖNDÜRÜR.
--BYTE OLARAK NEYE KARŞILIK GELDİĞİNİN DEĞERİNİ VERİYOR.
SELECT ASCII ('A')
SELECT CHAR(214)
--CHAR İSE TERSİ OLARAK KABUL GÖRÜR RAKAM HANGİ HARFE KARŞILIK GELİYOR.
SELECT ASCII(CHAR(49))
SELECT CHAR(ASCII('Ö'))

--SUBSTRING-BELLİ BİR NOKTADAN BELLİ BİR NOKTAYA KADAR OLAN ALANI ALMAMIZI SAĞLAR.
SELECT SUBSTRING('ÖMER FARUK ÇOLAKOĞLU',1,4)
--ÖRNEK YAPALIM
--O İLE BAŞLAYANLARI GETİR
SELECT * FROM USERS WHERE USERNAME_ LIKE 'O%'
--İLK HARFİ O OLANLARI GETİR
SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1)='O'
--A_KALKMAZO NUN SON KARAKTERİNİ YAZDIRALIM
--10. KARAKTERDEN İTİBAREN 1 TANE AL DEMEK .
SELECT SUBSTRING('A_KALKMAZO',10,1)
SELECT LEN('A_KALKMAZO')

--CHARINDEX:BİR STRİNG İÇİNDE BAŞKA STRİNG BULUP ONUN POZİSYONUNU BİZE SÖYLER.
SELECT CHARINDEX('F','ÖMER FARUK ÇOLAKOĞLU',0)
--ÇOLAK KAÇINCI HARFDEN SONRA BAŞLIYOR?
SELECT CHARINDEX('ÇOLAK','ÖMER FARUK ÇOLAKOĞLU',0)

--CONCAT: 2 VEYA DAHA FAZLA STRİNG İN BİRLEŞTİRİLMESİNİ SAĞLAR.
SELECT 'OMER'+'FARUK'+'COLAKOGLU'
SELECT CONCAT('OMER',' ','FARUK', ' ', 'COLAKOGLU' )
SELECT CONCAT_WS(' ','OMER','FARUK' ,'COLAKOGLU' )

--CONCAT
SELECT
USERNAME_+' '+PASSWORD_+' '+NAMESURNAME,
CONCAT(USERNAME_,' ',PASSWORD_,' ',NAMESURNAME),
CONCAT_WS(' ',USERNAME_,PASSWORD_,NAMESURNAME),

* FROM USERS

--FORMAT: TARİH YADA SAATLERİ İSTEDİĞİMİZ FORMATTA YAZDIRMAMIZI SAĞLAR
SELECT FORMAT(GETDATE(),'D','en-us')

--LEFT,RIGHT,LEN
SELECT LEFT('ÖMER ÇOLAKOĞLU',4)
SELECT RIGHT('ÖMER ÇOLAKOĞLU',4)
SELECT LEN('1234567890')

SELECT LEFT('ÖMER ÇOLAKOĞLU',4)
SELECT LEFT('ÖMER ÇOLAKOĞLU',CHARINDEX(' ','ÖMER ÇOLAKOĞLU')), RIGHT('ÖMER ÇOLAKOĞLU',LEN('ÖMER ÇOLAKOĞLU')-CHARINDEX(' ','ÖMER ÇOLAKOĞLU'))

SELECT
LEFT(NAMESURNAME,CHARINDEX(' ',NAMESURNAME)), RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME))
FROM USERS

--TRIM,LTRIM,RTRIM
SELECT TRIM(' ÖMER ÇOLAKOĞLU ')
SELECT TRIM(RTRIM(' ÖMER ÇOLAKOĞLU '))

--LOWER,UPPER,REVERSE,REPLICATE
SELECT LOWER('ömer')

SELECT UPPER('ömer')

SELECT REVERSE('ÖMER FARUK')

SELECT REPLICATE('0',10)

--REPLACE
SELECT 'ÖMER ÇOLAKOĞLU'
c


