--JOIN İLE YAPAMAYACAĞIMIZ BİR ÖRNEKDEN BAHSEDELİM .
--EN ÇOK HANGİ AY SATILDI...
SET STATISTICS IO ON 
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMA_FIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAM_ADET,
(
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
WHERE OD.ITEMID=ITM.ID --1 yerine ITM.ID Değerini gönderdik.
GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC --satış adedine göre tersden sıraladık.
) AS ENCOKSATILANAY
FROM
ITEMS ITM
ORDER BY ITM.ITEMNAME
/*
Ürünün aylara göre yapılan toplam satışını getirdik .
Toplam satışları , satış adedine göre sıraladık .
Top 1 diyerekde onun sonuncusunu aldık.
*/